**Efficacy of a biofungicide based on Trichoderma afroharzianum CP 24-6 against cacao frosty pod rot under different doses and application timings**

Wagner Meza-Maicelo, Anthony Cortez-Lázaro, Enistein R. Reyna-Rivera, Melissa I. Loja-Torres, Manuel Oliva-Cruz, Santos T. Leiva-Espinoza

## Manuscript

> Google Docs link: https://docs.google.com/document/d/14aq7TsjHVEtEmc8RWIXPntisPDMFuBR9aHXkDPf9bH8/edit?usp=sharing

## Database

> Google Sheets link: https://docs.google.com/spreadsheets/d/1DQDYUx_Miqkh9hipLRPc6hjWOd5jZDbAK42QcUIJ9hU/edit?usp=sharing

---

# SciHub: research pipeline repository

project-root/
  ├── analysis.qmd          # Script with data analysis (R/Python)
  ├── article.qmd           # Script for formatting the article
  ├── design/               # Experimental design and setup
  │   ├── design.qmd            # Document with experimental setup and planning
  │   └── labels.pdf            # Labels for experimental units or field trials
  ├── files/                # Supporting files for the project
  │   ├── images/               # Raw and processed images
  │   ├── zotero/               # Zotero library (.rds)
  │   └── template.docx         # Journal article template  
  ├── manuscript/           # Core outputs of the article
  │   ├── Figures               # Figures for the manuscript (.jpg & .eps)
  │   ├── ESM                   # Electronic Supplementary Material (ESM)
  │   └── draft.docx            # Manuscript text versions
  └── README.qmd            # Article title with authors:
                                # Manuscript link (Google Docs)
                                # Database link (Google Sheets)

---
